server:
  port: 8080
  host: "localhost"

log:
  level: "debug"
  file: "logs/server.log"

model:
  provider: "openai"
  api_key: "sk-xxxx"
  base_url: "https://api.openai.com/v1"
  model: "gpt-4o"
  temperature: 0.7
